<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <ApplicationIcon>icon.ico</ApplicationIcon>
    <StartupObject />
    <Version>3.9.0</Version>
    <Description>Simple mimicking Discord bot written with .Net Core and Discord.Net.</Description>
    <PackageLicenseUrl>https://github.com/Ervie/Homunculus/blob/master/LICENSE</PackageLicenseUrl>
    <PackageProjectUrl>https://github.com/Ervie/Homunculus</PackageProjectUrl>
    <RepositoryUrl>https://github.com/Ervie/Homunculus</RepositoryUrl>
    <Authors>Bartłomiej Buchała</Authors>
    <Company />
  </PropertyGroup>

  <ItemGroup>
    <None Remove="nlog.config" />
    <None Update="Resources\TextFiles\timedTasks.json">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Resources\TextFiles\streamMonday.json">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Resources\TextFiles\nyaaSearchPhrases.json">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Content Include="nlog.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Cronos" />
    <PackageReference Include="Discord.Net" />
    <PackageReference Include="Google.Apis" />
    <PackageReference Include="Google.Apis.YouTube.v3" />
    <PackageReference Include="Imgur.API" />
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="HtmlAgilityPack" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="NLog" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ImfFlipAPI.APISource.Core\ImfFlipAPI.APISource.Core.csproj" />
  </ItemGroup>


  <ItemGroup>
    <None Update="configuration.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Images\Reactions\jjj.gif">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\TextFiles\*.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
