//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarekMotykaBot.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MarekMotykaBot.Resources.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string charadeEnd {
            get {
                return ResourceManager.GetString("charadeEnd", resourceCulture);
            }
        }
        
        internal static string charadeReset {
            get {
                return ResourceManager.GetString("charadeReset", resourceCulture);
            }
        }
        
        internal static string customCommandLog {
            get {
                return ResourceManager.GetString("customCommandLog", resourceCulture);
            }
        }
        
        internal static string customDeleteLog {
            get {
                return ResourceManager.GetString("customDeleteLog", resourceCulture);
            }
        }
        
        internal static string customEditLog {
            get {
                return ResourceManager.GetString("customEditLog", resourceCulture);
            }
        }
        
        internal static string customReactionLog {
            get {
                return ResourceManager.GetString("customReactionLog", resourceCulture);
            }
        }
        
        internal static string daysAgo {
            get {
                return ResourceManager.GetString("daysAgo", resourceCulture);
            }
        }
        
        internal static string declineCommand {
            get {
                return ResourceManager.GetString("declineCommand", resourceCulture);
            }
        }
        
        internal static string derpQuote {
            get {
                return ResourceManager.GetString("derpQuote", resourceCulture);
            }
        }
        
        internal static string derpQuote2 {
            get {
                return ResourceManager.GetString("derpQuote2", resourceCulture);
            }
        }
        
        internal static string derpQuote3 {
            get {
                return ResourceManager.GetString("derpQuote3", resourceCulture);
            }
        }
        
        internal static string doctor {
            get {
                return ResourceManager.GetString("doctor", resourceCulture);
            }
        }
        
        internal static string eggString {
            get {
                return ResourceManager.GetString("eggString", resourceCulture);
            }
        }
        
        internal static string finishingBlow {
            get {
                return ResourceManager.GetString("finishingBlow", resourceCulture);
            }
        }
        
        internal static string genkiDama {
            get {
                return ResourceManager.GetString("genkiDama", resourceCulture);
            }
        }
        
        internal static string girlfriend {
            get {
                return ResourceManager.GetString("girlfriend", resourceCulture);
            }
        }
        
        internal static string head {
            get {
                return ResourceManager.GetString("head", resourceCulture);
            }
        }
        
        internal static string husbandoBest {
            get {
                return ResourceManager.GetString("husbandoBest", resourceCulture);
            }
        }
        
        internal static string husbandoBetter {
            get {
                return ResourceManager.GetString("husbandoBetter", resourceCulture);
            }
        }
        
        internal static string impossible {
            get {
                return ResourceManager.GetString("impossible", resourceCulture);
            }
        }
        
        internal static string inTheAss {
            get {
                return ResourceManager.GetString("inTheAss", resourceCulture);
            }
        }
        
        internal static string inTheJar {
            get {
                return ResourceManager.GetString("inTheJar", resourceCulture);
            }
        }
        
        internal static string job {
            get {
                return ResourceManager.GetString("job", resourceCulture);
            }
        }
        
        internal static string lateArrivalMessage1 {
            get {
                return ResourceManager.GetString("lateArrivalMessage1", resourceCulture);
            }
        }
        
        internal static string lateArrivalMessage2 {
            get {
                return ResourceManager.GetString("lateArrivalMessage2", resourceCulture);
            }
        }
        
        internal static string legiaWarszawa {
            get {
                return ResourceManager.GetString("legiaWarszawa", resourceCulture);
            }
        }
        
        internal static string listCommands {
            get {
                return ResourceManager.GetString("listCommands", resourceCulture);
            }
        }
        
        internal static string marekWaifus {
            get {
                return ResourceManager.GetString("marekWaifus", resourceCulture);
            }
        }
        
        internal static string masterThesis {
            get {
                return ResourceManager.GetString("masterThesis", resourceCulture);
            }
        }
        
        internal static string missedThrow {
            get {
                return ResourceManager.GetString("missedThrow", resourceCulture);
            }
        }
        
        internal static string missedThrow2 {
            get {
                return ResourceManager.GetString("missedThrow2", resourceCulture);
            }
        }
        
        internal static string noNumber {
            get {
                return ResourceManager.GetString("noNumber", resourceCulture);
            }
        }
        
        internal static string parameters {
            get {
                return ResourceManager.GetString("parameters", resourceCulture);
            }
        }
        
        internal static string preemptiveAttack {
            get {
                return ResourceManager.GetString("preemptiveAttack", resourceCulture);
            }
        }
        
        internal static string quoteForToday {
            get {
                return ResourceManager.GetString("quoteForToday", resourceCulture);
            }
        }
        
        internal static string rabbitMissing {
            get {
                return ResourceManager.GetString("rabbitMissing", resourceCulture);
            }
        }
        
        internal static string runAway {
            get {
                return ResourceManager.GetString("runAway", resourceCulture);
            }
        }
        
        internal static string secretGiftDeny {
            get {
                return ResourceManager.GetString("secretGiftDeny", resourceCulture);
            }
        }
        
        internal static string shitString {
            get {
                return ResourceManager.GetString("shitString", resourceCulture);
            }
        }
        
        internal static string snoring {
            get {
                return ResourceManager.GetString("snoring", resourceCulture);
            }
        }
        
        internal static string backlog {
            get {
                return ResourceManager.GetString("backlog", resourceCulture);
            }
        }
        
        internal static string swearWordCounterEntry {
            get {
                return ResourceManager.GetString("swearWordCounterEntry", resourceCulture);
            }
        }
        
        internal static string swearWordCounterHeader {
            get {
                return ResourceManager.GetString("swearWordCounterHeader", resourceCulture);
            }
        }
        
        internal static string tails {
            get {
                return ResourceManager.GetString("tails", resourceCulture);
            }
        }
        
        internal static string thesisDefense {
            get {
                return ResourceManager.GetString("thesisDefense", resourceCulture);
            }
        }
        
        internal static string today {
            get {
                return ResourceManager.GetString("today", resourceCulture);
            }
        }
        
        internal static string toldYou {
            get {
                return ResourceManager.GetString("toldYou", resourceCulture);
            }
        }
        
        internal static string tooMuch {
            get {
                return ResourceManager.GetString("tooMuch", resourceCulture);
            }
        }
        
        internal static string waifuBest {
            get {
                return ResourceManager.GetString("waifuBest", resourceCulture);
            }
        }
        
        internal static string waifuBetter {
            get {
                return ResourceManager.GetString("waifuBetter", resourceCulture);
            }
        }
        
        internal static string waifuEqual {
            get {
                return ResourceManager.GetString("waifuEqual", resourceCulture);
            }
        }
        
        internal static string waifuShit {
            get {
                return ResourceManager.GetString("waifuShit", resourceCulture);
            }
        }
        
        internal static string waitForIt {
            get {
                return ResourceManager.GetString("waitForIt", resourceCulture);
            }
        }
        
        internal static string wrongQuestion {
            get {
                return ResourceManager.GetString("wrongQuestion", resourceCulture);
            }
        }
        
        internal static string yesterday {
            get {
                return ResourceManager.GetString("yesterday", resourceCulture);
            }
        }
        
        internal static string ytNotFound {
            get {
                return ResourceManager.GetString("ytNotFound", resourceCulture);
            }
        }
        
        internal static string onlyErina {
            get {
                return ResourceManager.GetString("onlyErina", resourceCulture);
            }
        }
        
        internal static string flagReset {
            get {
                return ResourceManager.GetString("flagReset", resourceCulture);
            }
        }
        
        internal static string whyWouldIDoThat {
            get {
                return ResourceManager.GetString("whyWouldIDoThat", resourceCulture);
            }
        }
        
        internal static string added {
            get {
                return ResourceManager.GetString("added", resourceCulture);
            }
        }
        
        internal static string removed {
            get {
                return ResourceManager.GetString("removed", resourceCulture);
            }
        }
        
        internal static string versionHeader {
            get {
                return ResourceManager.GetString("versionHeader", resourceCulture);
            }
        }
        
        internal static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        internal static string translations {
            get {
                return ResourceManager.GetString("translations", resourceCulture);
            }
        }
        
        internal static string watchedRead {
            get {
                return ResourceManager.GetString("watchedRead", resourceCulture);
            }
        }
        
        internal static string helionPassword {
            get {
                return ResourceManager.GetString("helionPassword", resourceCulture);
            }
        }
        
        internal static string helionUser {
            get {
                return ResourceManager.GetString("helionUser", resourceCulture);
            }
        }
        
        internal static string utRotationChange {
            get {
                return ResourceManager.GetString("utRotationChange", resourceCulture);
            }
        }
        
        internal static string currentMapRotationHeader {
            get {
                return ResourceManager.GetString("currentMapRotationHeader", resourceCulture);
            }
        }
        
        internal static string currentMapHeader {
            get {
                return ResourceManager.GetString("currentMapHeader", resourceCulture);
            }
        }
        
        internal static string wedding {
            get {
                return ResourceManager.GetString("wedding", resourceCulture);
            }
        }
        
        internal static string quarantine {
            get {
                return ResourceManager.GetString("quarantine", resourceCulture);
            }
        }
        
        internal static string streamDayChanged {
            get {
                return ResourceManager.GetString("streamDayChanged", resourceCulture);
            }
        }
        
        internal static string lonkStole {
            get {
                return ResourceManager.GetString("lonkStole", resourceCulture);
            }
        }
        
        internal static string drunk {
            get {
                return ResourceManager.GetString("drunk", resourceCulture);
            }
        }
    }
}
