//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarekMotykaBot.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MarekMotykaBot.Resources.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O bocie.
        /// </summary>
        internal static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodano {0}.
        /// </summary>
        internal static string added {
            get {
                return ResourceManager.GetString("added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozkładówka (backlog).
        /// </summary>
        internal static string backlog {
            get {
                return ResourceManager.GetString("backlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koniec haseł!.
        /// </summary>
        internal static string charadeEnd {
            get {
                return ResourceManager.GetString("charadeEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kesz do kalamburów zresetowany..
        /// </summary>
        internal static string charadeReset {
            get {
                return ResourceManager.GetString("charadeReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktualna rotacja:.
        /// </summary>
        internal static string currentMapRotationHeader {
            get {
                return ResourceManager.GetString("currentMapRotationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wywołano komendę {0} modułu {1} dla użytkownika {2} w kanale {3}.
        /// </summary>
        internal static string customCommandLog {
            get {
                return ResourceManager.GetString("customCommandLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownik {0} w kanale {1} usunął wiadomość o treści: {2}.
        /// </summary>
        internal static string customDeleteLog {
            get {
                return ResourceManager.GetString("customDeleteLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownik {0} w kanale {1} zmienił wiadomość: {2} -&gt; {3}.
        /// </summary>
        internal static string customEditLog {
            get {
                return ResourceManager.GetString("customEditLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodano reakcję {0} dla wiadomości użytkownika {1} o treści {2} w kanale {3}.
        /// </summary>
        internal static string customReactionLog {
            get {
                return ResourceManager.GetString("customReactionLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} dni temu..
        /// </summary>
        internal static string daysAgo {
            get {
                return ResourceManager.GetString("daysAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z {0} to se możesz... to wiesz co se możesz!.
        /// </summary>
        internal static string declineCommand {
            get {
                return ResourceManager.GetString("declineCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Księga DerpRoomu mówi wyraźnie....
        /// </summary>
        internal static string derpQuote {
            get {
                return ResourceManager.GetString("derpQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W Księdze DerpRoomu napisane jest jasno....
        /// </summary>
        internal static string derpQuote2 {
            get {
                return ResourceManager.GetString("derpQuote2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jak pisze w Księdze DerpRoomu czarno na białym....
        /// </summary>
        internal static string derpQuote3 {
            get {
                return ResourceManager.GetString("derpQuote3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, ale teraz się doktoryzuję..
        /// </summary>
        internal static string doctor {
            get {
                return ResourceManager.GetString("doctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JAJCO.
        /// </summary>
        internal static string eggString {
            get {
                return ResourceManager.GetString("eggString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HISSATSU.
        /// </summary>
        internal static string finishingBlow {
            get {
                return ResourceManager.GetString("finishingBlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flaga zresetowana..
        /// </summary>
        internal static string flagReset {
            get {
                return ResourceManager.GetString("flagReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GÓWNO-DAMA!!!.
        /// </summary>
        internal static string genkiDama {
            get {
                return ResourceManager.GetString("genkiDama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, akurat wyszedłem z Martyną..
        /// </summary>
        internal static string girlfriend {
            get {
                return ResourceManager.GetString("girlfriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orzeł.
        /// </summary>
        internal static string head {
            get {
                return ResourceManager.GetString("head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helion password:.
        /// </summary>
        internal static string helionPassword {
            get {
                return ResourceManager.GetString("helionPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helion user e-mail:.
        /// </summary>
        internal static string helionUser {
            get {
                return ResourceManager.GetString("helionUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} najlepszy..
        /// </summary>
        internal static string husbandoBest {
            get {
                return ResourceManager.GetString("husbandoBest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} lepszy..
        /// </summary>
        internal static string husbandoBetter {
            get {
                return ResourceManager.GetString("husbandoBetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panieee, tak to się nie da..
        /// </summary>
        internal static string impossible {
            get {
                return ResourceManager.GetString("impossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...w dupie!.
        /// </summary>
        internal static string inTheAss {
            get {
                return ResourceManager.GetString("inTheAss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...w słoiku!.
        /// </summary>
        internal static string inTheJar {
            get {
                return ResourceManager.GetString("inTheJar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, teraz pracuję..
        /// </summary>
        internal static string job {
            get {
                return ResourceManager.GetString("job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, mordo! Autobus mi uciekł i się spóźniłem..
        /// </summary>
        internal static string lateArrivalMessage1 {
            get {
                return ResourceManager.GetString("lateArrivalMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stary, wybacz spóźnienie! Myślałem, że też się spóźnisz..
        /// </summary>
        internal static string lateArrivalMessage2 {
            get {
                return ResourceManager.GetString("lateArrivalMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legia Warszawa to najlepszy klub, kto nie wierzy, to chuj mu w dziób!.
        /// </summary>
        internal static string legiaWarszawa {
            get {
                return ResourceManager.GetString("legiaWarszawa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elo mordy, tutaj są komendy.
        /// </summary>
        internal static string listCommands {
            get {
                return ResourceManager.GetString("listCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} jest najlepsza! &lt;3.
        /// </summary>
        internal static string marekWaifus {
            get {
                return ResourceManager.GetString("marekWaifus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, ale muszę pisać magisterkę..
        /// </summary>
        internal static string masterThesis {
            get {
                return ResourceManager.GetString("masterThesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O kuźwa, nie trafiłem! Sorry {0} mordo!.
        /// </summary>
        internal static string missedThrow {
            get {
                return ResourceManager.GetString("missedThrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tsk... Nie trafiłem..
        /// </summary>
        internal static string missedThrow2 {
            get {
                return ResourceManager.GetString("missedThrow2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ni ma liczby, rzucam zwykłą..
        /// </summary>
        internal static string noNumber {
            get {
                return ResourceManager.GetString("noNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jak Nakiri to tylko Erina! Reszta to shit!.
        /// </summary>
        internal static string onlyErina {
            get {
                return ResourceManager.GetString("onlyErina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parametry: {0}.
        /// </summary>
        internal static string parameters {
            get {
                return ResourceManager.GetString("parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atak bez ostrzeżenia!.
        /// </summary>
        internal static string preemptiveAttack {
            get {
                return ResourceManager.GetString("preemptiveAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cytat na dziś:.
        /// </summary>
        internal static string quoteForToday {
            get {
                return ResourceManager.GetString("quoteForToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lonk grubasie, gdzie rabbit?!.
        /// </summary>
        internal static string rabbitMissing {
            get {
                return ResourceManager.GetString("rabbitMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usunięto {0}.
        /// </summary>
        internal static string removed {
            get {
                return ResourceManager.GetString("removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spierdalamyyyy!.
        /// </summary>
        internal static string runAway {
            get {
                return ResourceManager.GetString("runAway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Słucham się tylko {0}!.
        /// </summary>
        internal static string secretGiftDeny {
            get {
                return ResourceManager.GetString("secretGiftDeny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GÓWNO.
        /// </summary>
        internal static string shitString {
            get {
                return ResourceManager.GetString("shitString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chrrr... chrrr... chrrr....
        /// </summary>
        internal static string snoring {
            get {
                return ResourceManager.GetString("snoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} do tej pory użył słowa  &quot;{1}&quot; {2} razy..
        /// </summary>
        internal static string swearWordCounterEntry {
            get {
                return ResourceManager.GetString("swearWordCounterEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zliczam brzydkie słowa!.
        /// </summary>
        internal static string swearWordCounterHeader {
            get {
                return ResourceManager.GetString("swearWordCounterHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reszka.
        /// </summary>
        internal static string tails {
            get {
                return ResourceManager.GetString("tails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, ale muszę uczyć się na obronę..
        /// </summary>
        internal static string thesisDefense {
            get {
                return ResourceManager.GetString("thesisDefense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tytuł.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dzisiaj..
        /// </summary>
        internal static string today {
            get {
                return ResourceManager.GetString("today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ech {0}, przecież mówiłem Ci że z {1} to se możesz... To wiesz co se możesz!.
        /// </summary>
        internal static string toldYou {
            get {
                return ResourceManager.GetString("toldYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Za dużo :/.
        /// </summary>
        internal static string tooMuch {
            get {
                return ResourceManager.GetString("tooMuch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tłumaczenia.
        /// </summary>
        internal static string translations {
            get {
                return ResourceManager.GetString("translations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmieniono rotację map..
        /// </summary>
        internal static string utRotationChange {
            get {
                return ResourceManager.GetString("utRotationChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wersja.
        /// </summary>
        internal static string versionHeader {
            get {
                return ResourceManager.GetString("versionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} najlepsza..
        /// </summary>
        internal static string waifuBest {
            get {
                return ResourceManager.GetString("waifuBest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} lepsza..
        /// </summary>
        internal static string waifuBetter {
            get {
                return ResourceManager.GetString("waifuBetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obie świetne &lt;3!.
        /// </summary>
        internal static string waifuEqual {
            get {
                return ResourceManager.GetString("waifuEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} najlepsza, reszta to shit!.
        /// </summary>
        internal static string waifuShit {
            get {
                return ResourceManager.GetString("waifuShit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patrzcie chłopaki jak mu pocisnę....
        /// </summary>
        internal static string waitForIt {
            get {
                return ResourceManager.GetString("waitForIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obejrzane/przeczytane przez:.
        /// </summary>
        internal static string watchedRead {
            get {
                return ResourceManager.GetString("watchedRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czemu ja się zawahałem żeby strzelić? Mam wyrzuty sumienia?.
        /// </summary>
        internal static string whyWouldIDoThat {
            get {
                return ResourceManager.GetString("whyWouldIDoThat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Złe pytanie..
        /// </summary>
        internal static string wrongQuestion {
            get {
                return ResourceManager.GetString("wrongQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wczoraj..
        /// </summary>
        internal static string yesterday {
            get {
                return ResourceManager.GetString("yesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie znalazłem takiego filmu jak {0}..
        /// </summary>
        internal static string ytNotFound {
            get {
                return ResourceManager.GetString("ytNotFound", resourceCulture);
            }
        }
    }
}
