//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarekMotykaBot.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MarekMotykaBot.Resources.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Koniec haseł! ähnelt.
        /// </summary>
        internal static string charadeEnd {
            get {
                return ResourceManager.GetString("charadeEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kesz do kalamburów zresetowany. ähnelt.
        /// </summary>
        internal static string charadeReset {
            get {
                return ResourceManager.GetString("charadeReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wywołano komendę {0} modułu {1} dla użytkownika {2} w kanale {3} ähnelt.
        /// </summary>
        internal static string customCommandLog {
            get {
                return ResourceManager.GetString("customCommandLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Użytkownik {0} w kanale {1} usunął wiadomość o treści: {2} ähnelt.
        /// </summary>
        internal static string customDeleteLog {
            get {
                return ResourceManager.GetString("customDeleteLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Użytkownik {0} w kanale {1} zmienił wiadomość: {2} -&gt; {3} ähnelt.
        /// </summary>
        internal static string customEditLog {
            get {
                return ResourceManager.GetString("customEditLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dodano reakcję {0} dla wiadomości użytkownika {1} o treści {2} w kanale {3} ähnelt.
        /// </summary>
        internal static string customReactionLog {
            get {
                return ResourceManager.GetString("customReactionLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Z {0} to se możesz... to wiesz co se możesz! ähnelt.
        /// </summary>
        internal static string declineCommand {
            get {
                return ResourceManager.GetString("declineCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Księga DerpRoomu mówi wyraźnie... ähnelt.
        /// </summary>
        internal static string derpQuote {
            get {
                return ResourceManager.GetString("derpQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die W Księdze DerpRoomu napisane jest jasno... ähnelt.
        /// </summary>
        internal static string derpQuote2 {
            get {
                return ResourceManager.GetString("derpQuote2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Jak pisze w Księdze DerpRoomu czarno na białym... ähnelt.
        /// </summary>
        internal static string derpQuote3 {
            get {
                return ResourceManager.GetString("derpQuote3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sorry, ale teraz się doktoryzuję. ähnelt.
        /// </summary>
        internal static string doctor {
            get {
                return ResourceManager.GetString("doctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die JAJCO ähnelt.
        /// </summary>
        internal static string eggString {
            get {
                return ResourceManager.GetString("eggString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die HISSATSU ähnelt.
        /// </summary>
        internal static string finishingBlow {
            get {
                return ResourceManager.GetString("finishingBlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die GÓWNO-DAMA!!! ähnelt.
        /// </summary>
        internal static string genkiDama {
            get {
                return ResourceManager.GetString("genkiDama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sorry, akurat wyszedłem z Martyną. ähnelt.
        /// </summary>
        internal static string girlfriend {
            get {
                return ResourceManager.GetString("girlfriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Orzeł ähnelt.
        /// </summary>
        internal static string head {
            get {
                return ResourceManager.GetString("head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} najlepszy. ähnelt.
        /// </summary>
        internal static string husbandoBest {
            get {
                return ResourceManager.GetString("husbandoBest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} lepszy. ähnelt.
        /// </summary>
        internal static string husbandoBetter {
            get {
                return ResourceManager.GetString("husbandoBetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Panieee, tak to się nie da. ähnelt.
        /// </summary>
        internal static string impossible {
            get {
                return ResourceManager.GetString("impossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ...w słoiku! ähnelt.
        /// </summary>
        internal static string inTheJar {
            get {
                return ResourceManager.GetString("inTheJar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sorry, teraz pracuję. ähnelt.
        /// </summary>
        internal static string job {
            get {
                return ResourceManager.GetString("job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sorry, mordo! Autobus mi uciekł i się spóźniłem. ähnelt.
        /// </summary>
        internal static string lateArrivalMessage1 {
            get {
                return ResourceManager.GetString("lateArrivalMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stary, wybacz spóźnienie! Myślałem, że też się spóźnisz. ähnelt.
        /// </summary>
        internal static string lateArrivalMessage2 {
            get {
                return ResourceManager.GetString("lateArrivalMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Legia Warszawa to najlepszy klub, kto nie wierzy, to chuj mu w dziób! ähnelt.
        /// </summary>
        internal static string legiaWarszawa {
            get {
                return ResourceManager.GetString("legiaWarszawa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Elo mordy, tutaj są komendy ähnelt.
        /// </summary>
        internal static string listCommands {
            get {
                return ResourceManager.GetString("listCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} jest najlepsza! &lt;3 ähnelt.
        /// </summary>
        internal static string marekWaifus {
            get {
                return ResourceManager.GetString("marekWaifus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sorry, ale muszę pisać magisterkę. ähnelt.
        /// </summary>
        internal static string masterThesis {
            get {
                return ResourceManager.GetString("masterThesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die O kuźwa, nie trafiłem! Sorry {0} mordo! ähnelt.
        /// </summary>
        internal static string missedThrow {
            get {
                return ResourceManager.GetString("missedThrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tsk... Nie trafiłem. ähnelt.
        /// </summary>
        internal static string missedThrow2 {
            get {
                return ResourceManager.GetString("missedThrow2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ni ma liczby, rzucam zwykłą. ähnelt.
        /// </summary>
        internal static string noNumber {
            get {
                return ResourceManager.GetString("noNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Parametry: {0} ähnelt.
        /// </summary>
        internal static string parameters {
            get {
                return ResourceManager.GetString("parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cytat na dziś: ähnelt.
        /// </summary>
        internal static string quoteForToday {
            get {
                return ResourceManager.GetString("quoteForToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spierdalamyyyy! ähnelt.
        /// </summary>
        internal static string runAway {
            get {
                return ResourceManager.GetString("runAway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Słucham się tylko {0}! ähnelt.
        /// </summary>
        internal static string secretGiftDeny {
            get {
                return ResourceManager.GetString("secretGiftDeny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die GÓWNO ähnelt.
        /// </summary>
        internal static string shitString {
            get {
                return ResourceManager.GetString("shitString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Chrrr... chrrr... chrrr... ähnelt.
        /// </summary>
        internal static string snoring {
            get {
                return ResourceManager.GetString("snoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} do tej pory użył słowa  &quot;{1}&quot; {2} razy. ähnelt.
        /// </summary>
        internal static string swearWordCounterEntry {
            get {
                return ResourceManager.GetString("swearWordCounterEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zliczam brzydkie słowa! ähnelt.
        /// </summary>
        internal static string swearWordCounterHeader {
            get {
                return ResourceManager.GetString("swearWordCounterHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reszka ähnelt.
        /// </summary>
        internal static string tails {
            get {
                return ResourceManager.GetString("tails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sorry, ale muszę uczyć się na obronę. ähnelt.
        /// </summary>
        internal static string thesisDefense {
            get {
                return ResourceManager.GetString("thesisDefense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ech {0}, przecież mówiłem Ci że z {1} to se możesz... To wiesz co se możesz! ähnelt.
        /// </summary>
        internal static string toldYou {
            get {
                return ResourceManager.GetString("toldYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Za dużo :/ ähnelt.
        /// </summary>
        internal static string tooMuch {
            get {
                return ResourceManager.GetString("tooMuch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} najlepsza. ähnelt.
        /// </summary>
        internal static string waifuBest {
            get {
                return ResourceManager.GetString("waifuBest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} lepsza. ähnelt.
        /// </summary>
        internal static string waifuBetter {
            get {
                return ResourceManager.GetString("waifuBetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Obie świetne &lt;3! ähnelt.
        /// </summary>
        internal static string waifuEqual {
            get {
                return ResourceManager.GetString("waifuEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} najlepsza, reszta to shit! ähnelt.
        /// </summary>
        internal static string waifuShit {
            get {
                return ResourceManager.GetString("waifuShit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Patrzcie chłopaki jak mu pocisnę... ähnelt.
        /// </summary>
        internal static string waitForIt {
            get {
                return ResourceManager.GetString("waitForIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Złe pytanie. ähnelt.
        /// </summary>
        internal static string wrongQuestion {
            get {
                return ResourceManager.GetString("wrongQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nie znalazłem takiego filmu jak {0}. ähnelt.
        /// </summary>
        internal static string ytNotFound {
            get {
                return ResourceManager.GetString("ytNotFound", resourceCulture);
            }
        }
    }
}
