//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarekMotykaBot.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MarekMotykaBot.Resources.StringResources", typeof(StringResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z {0} to se możesz... to wiesz co se możesz!.
        /// </summary>
        internal static string declineCommand {
            get {
                return ResourceManager.GetString("declineCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} najlepszy..
        /// </summary>
        internal static string husbandoBest {
            get {
                return ResourceManager.GetString("husbandoBest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} lepszy..
        /// </summary>
        internal static string husbandoBetter {
            get {
                return ResourceManager.GetString("husbandoBetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legia Warszawa to najlepszy klub, kto nie wierzy, to chuj mu w dziób!.
        /// </summary>
        internal static string legiaWarszawa {
            get {
                return ResourceManager.GetString("legiaWarszawa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elo mordy, tutaj są komendy.
        /// </summary>
        internal static string listCommands {
            get {
                return ResourceManager.GetString("listCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, ale muszę pisać magisterkę..
        /// </summary>
        internal static string masterThesis {
            get {
                return ResourceManager.GetString("masterThesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GÓWNO.
        /// </summary>
        internal static string shitString {
            get {
                return ResourceManager.GetString("shitString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} najlepsza..
        /// </summary>
        internal static string waifuBest {
            get {
                return ResourceManager.GetString("waifuBest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} lepsza..
        /// </summary>
        internal static string waifuBetter {
            get {
                return ResourceManager.GetString("waifuBetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obie świetne &lt;3!.
        /// </summary>
        internal static string waifuEqual {
            get {
                return ResourceManager.GetString("waifuEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} najlepsza, reszta to shit!.
        /// </summary>
        internal static string waifuShit {
            get {
                return ResourceManager.GetString("waifuShit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patrzcie chłopaki jak mu pocisnę....
        /// </summary>
        internal static string waitForIt {
            get {
                return ResourceManager.GetString("waitForIt", resourceCulture);
            }
        }
    }
}
