//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarekMotykaBot.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MarekMotykaBot.Resources.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koniec haseł!.
        /// </summary>
        internal static string charadeEnd {
            get {
                return ResourceManager.GetString("charadeEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z {0} to se możesz... to wiesz co se możesz!.
        /// </summary>
        internal static string declineCommand {
            get {
                return ResourceManager.GetString("declineCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, ale teraz się doktoryzuję..
        /// </summary>
        internal static string doctor {
            get {
                return ResourceManager.GetString("doctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, akurat wyszedłem z Martyną..
        /// </summary>
        internal static string girlfriend {
            get {
                return ResourceManager.GetString("girlfriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orzeł.
        /// </summary>
        internal static string head {
            get {
                return ResourceManager.GetString("head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} najlepszy..
        /// </summary>
        internal static string husbandoBest {
            get {
                return ResourceManager.GetString("husbandoBest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} lepszy..
        /// </summary>
        internal static string husbandoBetter {
            get {
                return ResourceManager.GetString("husbandoBetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panieee, tak to się nie da..
        /// </summary>
        internal static string impossible {
            get {
                return ResourceManager.GetString("impossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...w słoiku!.
        /// </summary>
        internal static string inTheJar {
            get {
                return ResourceManager.GetString("inTheJar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, teraz pracuję..
        /// </summary>
        internal static string job {
            get {
                return ResourceManager.GetString("job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legia Warszawa to najlepszy klub, kto nie wierzy, to chuj mu w dziób!.
        /// </summary>
        internal static string legiaWarszawa {
            get {
                return ResourceManager.GetString("legiaWarszawa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elo mordy, tutaj są komendy.
        /// </summary>
        internal static string listCommands {
            get {
                return ResourceManager.GetString("listCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} jest najlepsza! &lt;3.
        /// </summary>
        internal static string marekWaifus {
            get {
                return ResourceManager.GetString("marekWaifus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, ale muszę pisać magisterkę..
        /// </summary>
        internal static string masterThesis {
            get {
                return ResourceManager.GetString("masterThesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ni ma liczby, rzucam zwykłą..
        /// </summary>
        internal static string noNumber {
            get {
                return ResourceManager.GetString("noNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spierdalamyyyy!.
        /// </summary>
        internal static string runAway {
            get {
                return ResourceManager.GetString("runAway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Słucham się tylko {0}!.
        /// </summary>
        internal static string secretGiftDeny {
            get {
                return ResourceManager.GetString("secretGiftDeny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GÓWNO.
        /// </summary>
        internal static string shitString {
            get {
                return ResourceManager.GetString("shitString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chrrr... chrrr... chrrr....
        /// </summary>
        internal static string snoring {
            get {
                return ResourceManager.GetString("snoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} do tej pory użył słowa  &quot;{1}&quot; {2} razy..
        /// </summary>
        internal static string swearWordCounterEntry {
            get {
                return ResourceManager.GetString("swearWordCounterEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zliczam brzydkie słowa!.
        /// </summary>
        internal static string swearWordCounterHeader {
            get {
                return ResourceManager.GetString("swearWordCounterHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reszka.
        /// </summary>
        internal static string tails {
            get {
                return ResourceManager.GetString("tails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, ale muszę uczyć się na obronę..
        /// </summary>
        internal static string thesisDefense {
            get {
                return ResourceManager.GetString("thesisDefense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Za dużo :/.
        /// </summary>
        internal static string tooMuch {
            get {
                return ResourceManager.GetString("tooMuch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} najlepsza..
        /// </summary>
        internal static string waifuBest {
            get {
                return ResourceManager.GetString("waifuBest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} lepsza..
        /// </summary>
        internal static string waifuBetter {
            get {
                return ResourceManager.GetString("waifuBetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obie świetne &lt;3!.
        /// </summary>
        internal static string waifuEqual {
            get {
                return ResourceManager.GetString("waifuEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} najlepsza, reszta to shit!.
        /// </summary>
        internal static string waifuShit {
            get {
                return ResourceManager.GetString("waifuShit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patrzcie chłopaki jak mu pocisnę....
        /// </summary>
        internal static string waitForIt {
            get {
                return ResourceManager.GetString("waitForIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie znalazłem takiego filmu jak {0}..
        /// </summary>
        internal static string ytNotFound {
            get {
                return ResourceManager.GetString("ytNotFound", resourceCulture);
            }
        }
    }
}
